apiVersion: v1
kind: Service
metadata:
  name: wso2am
spec:
  selector:
    app: wso2am
  ports:
    - name: https
      port: 9443
      targetPort: 9443
    - name: http
      port: 8280
      targetPort: 8280
    - name: https-secure
      port: 8243
      targetPort: 8243
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2am
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2am
  template:
    metadata:
      labels:
        app: wso2am
    spec:
      containers:
        - name: wso2am
          image: wso2/wso2am:latest
          ports:
            - containerPort: 9443
            - containerPort: 8280
            - containerPort: 8243
          # Sin variables de entorno para conexión externa a base de datos
